[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
good_lp = { version = "1.14.2", features = ["microlp"], default-features = false }
